// <auto-generated />
using System;
using AccommodationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccommodationService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251227175148_DateOnly")]
    partial class DateOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccommodationAmenity", b =>
                {
                    b.Property<Guid>("AccommodationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AmenitiesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccommodationId", "AmenitiesId");

                    b.HasIndex("AmenitiesId");

                    b.ToTable("AccommodationAmenity");
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Accommodation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAutoConfirm")
                        .HasColumnType("bit");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaximumNumberOfGuests")
                        .HasColumnType("int");

                    b.Property<int>("MinimumNumberOfGuests")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("Accommodation");
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Amenity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6e41134a-9d1b-480c-8fa2-abfa33207fb3"),
                            Description = "High-speed wireless internet",
                            Name = "Wi-Fi"
                        },
                        new
                        {
                            Id = new Guid("e363716d-52fc-46f7-94af-16fff53281d5"),
                            Description = "Air conditioning available",
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            Id = new Guid("0a1ea175-6027-43b3-a413-cc5013587bc5"),
                            Description = "Central or electric heating",
                            Name = "Heating"
                        },
                        new
                        {
                            Id = new Guid("db01bb33-3890-4738-a9a7-768a8c50b792"),
                            Description = "Hot water available in the property",
                            Name = "Hot Water"
                        },
                        new
                        {
                            Id = new Guid("391e4769-8a27-4c34-99fc-0217d813ed0e"),
                            Description = "Additional bedding for comfort",
                            Name = "Extra Pillows & Blankets"
                        },
                        new
                        {
                            Id = new Guid("81c43f95-2c71-40a7-8dd2-d77f34993d90"),
                            Description = "Curtains that block outside light",
                            Name = "Blackout Curtains"
                        },
                        new
                        {
                            Id = new Guid("5de67704-28bb-4a89-a45c-6b9e8b1b0271"),
                            Description = "Desk or dedicated work area",
                            Name = "Workspace"
                        },
                        new
                        {
                            Id = new Guid("50ee377c-f12b-4e48-9058-8462216dedc7"),
                            Description = "Wardrobe or closet available",
                            Name = "Wardrobe"
                        },
                        new
                        {
                            Id = new Guid("135570fc-de7f-4d26-b8f6-68c9129fecc6"),
                            Description = "Iron for clothing",
                            Name = "Iron"
                        },
                        new
                        {
                            Id = new Guid("ea0a467e-5eb2-44dc-bba2-694c72a03bf3"),
                            Description = "Hair dryer available",
                            Name = "Hair Dryer"
                        },
                        new
                        {
                            Id = new Guid("8666003a-7cdc-4980-8c2d-44699b53faf1"),
                            Description = "Kitchen suitable for cooking",
                            Name = "Fully Equipped Kitchen"
                        },
                        new
                        {
                            Id = new Guid("70254341-31d1-4875-9d09-ec7420d61eb4"),
                            Description = "Fridge for food storage",
                            Name = "Refrigerator"
                        },
                        new
                        {
                            Id = new Guid("b24d51f6-f6f6-4940-be70-9f276dde7bc4"),
                            Description = "Oven for baking or roasting",
                            Name = "Oven"
                        },
                        new
                        {
                            Id = new Guid("3ab31706-f9c6-4146-a28d-af801cb293a1"),
                            Description = "Stovetop for cooking",
                            Name = "Stove"
                        },
                        new
                        {
                            Id = new Guid("722f68de-a089-4af2-adb2-11e012fde5d3"),
                            Description = "Microwave oven available",
                            Name = "Microwave"
                        },
                        new
                        {
                            Id = new Guid("d9509b48-221e-4f3f-902c-5a089af09308"),
                            Description = "Dishwashing machine available",
                            Name = "Dishwasher"
                        },
                        new
                        {
                            Id = new Guid("689a5ee4-2c68-44c3-b0c5-a3f79d016260"),
                            Description = "Machine for making coffee",
                            Name = "Coffee Maker"
                        },
                        new
                        {
                            Id = new Guid("ec4fffc7-e49a-470e-90a2-687746e25720"),
                            Description = "Kettle for boiling water",
                            Name = "Electric Kettle"
                        },
                        new
                        {
                            Id = new Guid("fbc72261-1cd5-432d-8ae5-4495753008be"),
                            Description = "Toaster for bread or pastries",
                            Name = "Toaster"
                        },
                        new
                        {
                            Id = new Guid("1cc002dd-822e-4d6f-9104-18b681bd2010"),
                            Description = "Pots, pans, oil, salt, and spices",
                            Name = "Cooking Basics"
                        },
                        new
                        {
                            Id = new Guid("032aa451-8d57-41a2-af6b-fb579b548d8f"),
                            Description = "Television available",
                            Name = "TV"
                        },
                        new
                        {
                            Id = new Guid("519f19e7-8bcb-4d45-8af0-d6b5810ec005"),
                            Description = "Access to Netflix, Prime, etc.",
                            Name = "Streaming Services"
                        },
                        new
                        {
                            Id = new Guid("889df220-cf09-4f24-a7cc-feeb1af90f41"),
                            Description = "Assorted board games",
                            Name = "Board Games"
                        },
                        new
                        {
                            Id = new Guid("e19c4298-16fb-4e60-a45a-9f9b56200534"),
                            Description = "Books available for reading",
                            Name = "Books"
                        },
                        new
                        {
                            Id = new Guid("3c1f93b3-00c5-40d0-8da1-d760e1ae0540"),
                            Description = "Laundry washing machine",
                            Name = "Washing Machine"
                        },
                        new
                        {
                            Id = new Guid("304618b2-9e99-4369-9d67-733f27de92e4"),
                            Description = "Clothes dryer available",
                            Name = "Dryer"
                        },
                        new
                        {
                            Id = new Guid("41ded426-535e-44d1-b7de-d8325b304c12"),
                            Description = "Drying rack for clothes",
                            Name = "Drying Rack"
                        },
                        new
                        {
                            Id = new Guid("79335f1b-abad-41fd-acd0-b59839197b64"),
                            Description = "Private balcony area",
                            Name = "Balcony"
                        },
                        new
                        {
                            Id = new Guid("61b73ac4-118e-498e-be74-b6f769de499b"),
                            Description = "Outdoor terrace space",
                            Name = "Terrace"
                        },
                        new
                        {
                            Id = new Guid("e1604888-0934-4f62-8340-cd6ccc2c1f94"),
                            Description = "Garden area exclusive to guests",
                            Name = "Private Garden"
                        },
                        new
                        {
                            Id = new Guid("a78268e4-9c28-4684-99dc-1e2e9a8b5ab3"),
                            Description = "Outdoor grill for cooking",
                            Name = "BBQ Grill"
                        },
                        new
                        {
                            Id = new Guid("9d7bc35e-6bcf-4051-bdba-8d2a708c1849"),
                            Description = "Table and seating outdoors",
                            Name = "Outdoor Dining Area"
                        },
                        new
                        {
                            Id = new Guid("58239272-6c9d-40d5-a1c4-0b054da6c1da"),
                            Description = "Outdoor chairs, sofa, or loungers",
                            Name = "Patio Furniture"
                        },
                        new
                        {
                            Id = new Guid("5b9193c1-047f-44b2-bf6a-33bdf35a0d62"),
                            Description = "Dedicated private parking spot",
                            Name = "Private Parking"
                        },
                        new
                        {
                            Id = new Guid("4f436db4-5fa7-463d-a569-8804f07b73ec"),
                            Description = "Parking available on the street",
                            Name = "Street Parking"
                        },
                        new
                        {
                            Id = new Guid("d73ae4ec-1f44-485c-b5e4-63ee1831c7f0"),
                            Description = "Electric vehicle charging station",
                            Name = "EV Charger"
                        },
                        new
                        {
                            Id = new Guid("078e28f9-326d-465f-bf42-10df47baf9bc"),
                            Description = "Smoke detection system",
                            Name = "Smoke Detector"
                        },
                        new
                        {
                            Id = new Guid("f84e0261-b049-4452-aa7f-d1a7ae2d9f64"),
                            Description = "CO detection device",
                            Name = "Carbon Monoxide Detector"
                        },
                        new
                        {
                            Id = new Guid("c45c36ba-367d-4393-b5ff-36084c473210"),
                            Description = "Fire safety extinguisher",
                            Name = "Fire Extinguisher"
                        },
                        new
                        {
                            Id = new Guid("1f78908c-9203-4d00-9323-ad69f19e4d9a"),
                            Description = "Basic first aid supplies",
                            Name = "First Aid Kit"
                        });
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Availability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccommodationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.ToTable("Availability");
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccommodationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccommodationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("AccommodationAmenity", b =>
                {
                    b.HasOne("AccommodationService.Domain.Entities.Accommodation", null)
                        .WithMany()
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccommodationService.Domain.Entities.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Accommodation", b =>
                {
                    b.HasOne("AccommodationService.Domain.Entities.Location", "Location")
                        .WithOne("Accommodation")
                        .HasForeignKey("AccommodationService.Domain.Entities.Accommodation", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Availability", b =>
                {
                    b.HasOne("AccommodationService.Domain.Entities.Accommodation", "Accommodation")
                        .WithMany("Availabilities")
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Photo", b =>
                {
                    b.HasOne("AccommodationService.Domain.Entities.Accommodation", "Accommodation")
                        .WithMany("Photos")
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Accommodation", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Location", b =>
                {
                    b.Navigation("Accommodation");
                });
#pragma warning restore 612, 618
        }
    }
}
