// <auto-generated />
using System;
using AccommodationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccommodationService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251128172840_AddedAmenitySeeding")]
    partial class AddedAmenitySeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccommodationAmenity", b =>
                {
                    b.Property<Guid>("AccommodationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AmenitiesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccommodationId", "AmenitiesId");

                    b.HasIndex("AmenitiesId");

                    b.ToTable("AccommodationAmenity");
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Accommodation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAutoConfirm")
                        .HasColumnType("bit");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaximumNumberOfGuests")
                        .HasColumnType("int");

                    b.Property<int>("MinimumNumberOfGuests")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("Accommodation");
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Amenity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5399ea27-ca14-4717-a6f0-530525e2c406"),
                            Description = "High-speed wireless internet",
                            Name = "Wi-Fi"
                        },
                        new
                        {
                            Id = new Guid("677841ba-c64e-43b1-8c99-fce2125f2ad8"),
                            Description = "Air conditioning available",
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            Id = new Guid("effb512e-847e-4a2d-8c6f-1449b0ebb5ce"),
                            Description = "Central or electric heating",
                            Name = "Heating"
                        },
                        new
                        {
                            Id = new Guid("a751df3b-16bd-40a3-a810-09e994b9b792"),
                            Description = "Hot water available in the property",
                            Name = "Hot Water"
                        },
                        new
                        {
                            Id = new Guid("57dc2603-846f-46f2-a571-718c409fb2b7"),
                            Description = "Additional bedding for comfort",
                            Name = "Extra Pillows & Blankets"
                        },
                        new
                        {
                            Id = new Guid("b6b783c5-2c9a-4fd8-82e9-db04401e0d87"),
                            Description = "Curtains that block outside light",
                            Name = "Blackout Curtains"
                        },
                        new
                        {
                            Id = new Guid("883ae7f1-ac6f-4ff5-ad04-e75ee22f34d2"),
                            Description = "Desk or dedicated work area",
                            Name = "Workspace"
                        },
                        new
                        {
                            Id = new Guid("01684193-7e90-4f04-8ea1-a5dcf533b150"),
                            Description = "Wardrobe or closet available",
                            Name = "Wardrobe"
                        },
                        new
                        {
                            Id = new Guid("d2aadf15-132c-4d47-b407-68f10057425f"),
                            Description = "Iron for clothing",
                            Name = "Iron"
                        },
                        new
                        {
                            Id = new Guid("d7d2c920-8d62-4900-9926-8d8f02f0861e"),
                            Description = "Hair dryer available",
                            Name = "Hair Dryer"
                        },
                        new
                        {
                            Id = new Guid("20a167a4-d94e-4131-a415-9eec6e6fbcd3"),
                            Description = "Kitchen suitable for cooking",
                            Name = "Fully Equipped Kitchen"
                        },
                        new
                        {
                            Id = new Guid("22b89c5e-d41f-4705-8f4f-ecae301d7f1a"),
                            Description = "Fridge for food storage",
                            Name = "Refrigerator"
                        },
                        new
                        {
                            Id = new Guid("04771b32-22e8-4877-8d98-f05ba616dc1b"),
                            Description = "Oven for baking or roasting",
                            Name = "Oven"
                        },
                        new
                        {
                            Id = new Guid("24da175b-6e4e-4b9d-a104-5038855a86f4"),
                            Description = "Stovetop for cooking",
                            Name = "Stove"
                        },
                        new
                        {
                            Id = new Guid("33cbff6a-0b16-40b0-ad5c-4496213cefbc"),
                            Description = "Microwave oven available",
                            Name = "Microwave"
                        },
                        new
                        {
                            Id = new Guid("a1ac66d6-e164-4ff3-8b6e-2832d5f1f06e"),
                            Description = "Dishwashing machine available",
                            Name = "Dishwasher"
                        },
                        new
                        {
                            Id = new Guid("7ddbb4ba-2d1f-4b5c-ae24-ba98c096cd5a"),
                            Description = "Machine for making coffee",
                            Name = "Coffee Maker"
                        },
                        new
                        {
                            Id = new Guid("e96afaa8-2440-4fed-b95e-6d05f2a561b8"),
                            Description = "Kettle for boiling water",
                            Name = "Electric Kettle"
                        },
                        new
                        {
                            Id = new Guid("d99d1b20-3b22-473e-91cc-2327537bb40c"),
                            Description = "Toaster for bread or pastries",
                            Name = "Toaster"
                        },
                        new
                        {
                            Id = new Guid("bc52047e-a560-4592-88e0-e2ba807113e2"),
                            Description = "Pots, pans, oil, salt, and spices",
                            Name = "Cooking Basics"
                        },
                        new
                        {
                            Id = new Guid("1a7388ce-eb51-4301-9231-6be9c64f9303"),
                            Description = "Television available",
                            Name = "TV"
                        },
                        new
                        {
                            Id = new Guid("f7bca978-0dba-4aa2-a4fc-450c023bffb1"),
                            Description = "Access to Netflix, Prime, etc.",
                            Name = "Streaming Services"
                        },
                        new
                        {
                            Id = new Guid("7c3125aa-d9ab-467d-9a9d-d7fa22ee1e10"),
                            Description = "Assorted board games",
                            Name = "Board Games"
                        },
                        new
                        {
                            Id = new Guid("255ef502-43c2-42f4-8b0b-8e05f60eb537"),
                            Description = "Books available for reading",
                            Name = "Books"
                        },
                        new
                        {
                            Id = new Guid("68324f8f-555e-444b-ae00-9e91c2baccf6"),
                            Description = "Laundry washing machine",
                            Name = "Washing Machine"
                        },
                        new
                        {
                            Id = new Guid("4d0fb2f2-b63f-458e-bc63-a613265ddab7"),
                            Description = "Clothes dryer available",
                            Name = "Dryer"
                        },
                        new
                        {
                            Id = new Guid("fa1dec29-cc4e-4bb3-b526-e83adafce25f"),
                            Description = "Drying rack for clothes",
                            Name = "Drying Rack"
                        },
                        new
                        {
                            Id = new Guid("bea91001-d5c5-4868-8295-9a36caab68cc"),
                            Description = "Private balcony area",
                            Name = "Balcony"
                        },
                        new
                        {
                            Id = new Guid("6b17c64d-9484-48ec-8742-d746c0d4fcd3"),
                            Description = "Outdoor terrace space",
                            Name = "Terrace"
                        },
                        new
                        {
                            Id = new Guid("a8e24c14-76e2-424a-81db-cd4ffa341fe7"),
                            Description = "Garden area exclusive to guests",
                            Name = "Private Garden"
                        },
                        new
                        {
                            Id = new Guid("acf2b9dc-afc8-4367-9f6a-d486e9e80644"),
                            Description = "Outdoor grill for cooking",
                            Name = "BBQ Grill"
                        },
                        new
                        {
                            Id = new Guid("d64e5b47-33fa-490b-9331-184a77bbfb03"),
                            Description = "Table and seating outdoors",
                            Name = "Outdoor Dining Area"
                        },
                        new
                        {
                            Id = new Guid("5e6c4ff6-718a-4fe1-a752-2316eff39d66"),
                            Description = "Outdoor chairs, sofa, or loungers",
                            Name = "Patio Furniture"
                        },
                        new
                        {
                            Id = new Guid("56803dea-baf6-4293-9a0a-56d79afcaf1e"),
                            Description = "Dedicated private parking spot",
                            Name = "Private Parking"
                        },
                        new
                        {
                            Id = new Guid("c6914809-f9f1-4a4f-89f5-fa4238ad0d3b"),
                            Description = "Parking available on the street",
                            Name = "Street Parking"
                        },
                        new
                        {
                            Id = new Guid("fd8707f0-6750-4a44-90fa-861b5410c265"),
                            Description = "Electric vehicle charging station",
                            Name = "EV Charger"
                        },
                        new
                        {
                            Id = new Guid("fec9e4be-4635-42cb-b294-a71beb4a3487"),
                            Description = "Smoke detection system",
                            Name = "Smoke Detector"
                        },
                        new
                        {
                            Id = new Guid("27556265-bcc0-415d-82a9-491360b25149"),
                            Description = "CO detection device",
                            Name = "Carbon Monoxide Detector"
                        },
                        new
                        {
                            Id = new Guid("62165eac-7085-4b64-a180-dc9629a218a1"),
                            Description = "Fire safety extinguisher",
                            Name = "Fire Extinguisher"
                        },
                        new
                        {
                            Id = new Guid("16407b8b-eaa2-4045-8171-8de0701bed3a"),
                            Description = "Basic first aid supplies",
                            Name = "First Aid Kit"
                        });
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Availability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccommodationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.ToTable("Availability");
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccommodationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccommodationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("AccommodationAmenity", b =>
                {
                    b.HasOne("AccommodationService.Domain.Entities.Accommodation", null)
                        .WithMany()
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccommodationService.Domain.Entities.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Accommodation", b =>
                {
                    b.HasOne("AccommodationService.Domain.Entities.Location", "Location")
                        .WithOne("Accommodation")
                        .HasForeignKey("AccommodationService.Domain.Entities.Accommodation", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Availability", b =>
                {
                    b.HasOne("AccommodationService.Domain.Entities.Accommodation", "Accommodation")
                        .WithMany("Availabilities")
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Photo", b =>
                {
                    b.HasOne("AccommodationService.Domain.Entities.Accommodation", "Accommodation")
                        .WithMany("Photos")
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Accommodation", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("AccommodationService.Domain.Entities.Location", b =>
                {
                    b.Navigation("Accommodation");
                });
#pragma warning restore 612, 618
        }
    }
}
